#!/bin/sh

if [ "$IFACE" != "eth0" ]; then
    exit 0
fi

# Only run from ifup.
if [ "$MODE" != start ]; then
    exit 0
fi

ipaddress=`facter ipaddress`
echo "Update rivendellnas/$ipaddress in dnsmasq"

echo "host-record=rivendellnas,$ipaddress" > /etc/dnsmasq.d/rivendellnas
invoke-rc.d dnsmasq restart || true
