#!/bin/bash

# REMOVEME Migration for ticket #8
if ! grep VISUAL ~/.xsessionrc; then
  echo "export VISUAL=gedit" >> ~/.xsessionrc
fi

if [ ! -f ~/.homesync ]; then
  rsync -a /etc/skel/ ~/ && touch ~/.homesync
fi

# Remove .rdairplaylock lock (#649)
pgrep rdairplay > /dev/null || rm -f ~/.rdairplaylock
