#!/bin/bash

if ! grep VISUAL ~/.xsessionrc; then
    echo "export VISUAL=mousepad" >> ~/.xsessionrc
else
    sed -i 's/export VISUAL=gedit/export VISUAL=mousepad/' ~/.xsessionrc
fi

if [ ! -f ~/.homesync ]; then
    rsync -a /etc/skel/ ~/
    touch ~/.homesync
fi

# Remove .rdairplaylock lock (#649)
pgrep rdairplay > /dev/null || rm -f ~/.rdairplaylock

# Disable DPMS
xset s off
xset -dpms
