#!/bin/bash

PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin

backup_dir=${BACKUP_DIR:-/srv/rivendell/backup}
working_file="$backup_dir/last-dump"
backup_file="$backup_dir/database-`date +%Y%m%d-%H%M`.sql"
shelf_life=7

# Code from http://ajdiaz.wordpress.com/2008/02/09/bash-ini-parser/
function cfg_parser() {
    ini="$(<$1)"                # read the file
    ini="${ini//[/\[}"          # escape [
    ini="${ini//]/\]}"          # escape ]
    IFS=$'\n' && ini=( ${ini} ) # convert to line-array
    ini=( ${ini[*]//;*/} )      # remove comments with ;
    ini=( ${ini[*]/\    =/=} )  # remove tabs before =
    ini=( ${ini[*]/=\   /=} )   # remove tabs be =
    ini=( ${ini[*]/\ =\ /=} )   # remove anything with a space around =
    ini=( ${ini[*]/#\\[/\}$'\n'cfg.section.} ) # set section prefix
    ini=( ${ini[*]/%\\]/ \(} )    # convert text2function (1)
    ini=( ${ini[*]/=/=\( } )    # convert item to array
    ini=( ${ini[*]/%/ \)} )     # close array parenthesis
    ini=( ${ini[*]/%\\ \)/ \\} ) # the multiline trick
    ini=( ${ini[*]/%\( \)/\(\) \{} ) # convert text2function (2)
    ini=( ${ini[*]/%\} \)/\}} ) # remove extra parenthesis
    ini[0]="" # remove first element
    ini[${#ini[*]} + 1]='}'    # add the last brace
    eval "$(echo "${ini[*]}")" # eval the result
}

cfg_parser '/etc/rd.conf'
cfg.section.mySQL

mysqldump --opt --single-transaction -u $Loginname -p$Password $Database > $working_file
if [ $? == 0 ]; then
    mv $working_file $backup_file
else
    echo "mysqldump failed"
fi

keep_releases=15
ls -r $backup_dir/database-*.sql | tail -n +$keep_releases | xargs -r rm
