#!/bin/bash

LOG_TOPIC="rivendell-migratedb"
LOG_TOPIC_OUT="$LOG_TOPIC-out[$$]"
LOG_TOPIC_ERR="$LOG_TOPIC-err[$$]"

exec > >(logger -t "$LOG_TOPIC_OUT")
exec 2> >(logger -t "$LOG_TOPIC_ERR" )

if ! mysql mysql -NBe 'show databases' | grep -q Rivendell; then
    echo "Create Rivendell database"

    mysqladmin create Rivendell
    mysql mysql -e "GRANT ALL ON Rivendell.* TO 'rduser' IDENTIFIED BY 'letmein'"
    mysqladmin flush-privileges
fi

if ! mysql Rivendell -NBe 'show tables' | grep -q CART; then
    echo "Create Rivendell tables"
    mysql Rivendell < /usr/local/share/rivendell/rivendell.sql
fi

if ! mysql mysql -NBe 'show databases' | grep -q import; then
    echo "Create Rivendell Import database"

    mysqladmin create import
    mysql mysql -e "GRANT ALL PRIVILEGES ON import.* TO 'import'@'localhost' IDENTIFIED BY 'import'"
    mysqladmin flush-privileges
fi

if grep -q rivendellallbox /boot/current.yml; then
    /usr/local/bin/rivendell station add --name=rivendellallbox --ip-address=127.0.0.2
fi
